version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/creamybites
      SPRING_DATASOURCE_USERNAME: jarvis
      SPRING_DATASOURCE_PASSWORD: 8171@Jarvis
	network_mode: "host"
